#!/bin/bash

# To force a specific version of SalesPlatform, set this variable:
#

# Used in this script only
#
current_version_dir=${OPENSHIFT_DATA_DIR}current

#
# If SalesPlatform is already installed in the current gear, there
# is nothing to build :-)
#
[ -d "${current_version_dir}" ] && exit 0

install_version='6.4.0-201512'

# Download and install SalesPlatform
#

install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${install_version}
mkdir -p $install_dir

pushd ${install_dir} >/dev/null

curl -Ls http://downloads.sourceforge.net/project/salesplatform/salesplatform-vtigercrm-${install_version}.tar.gz > salesplatform-vtigercrm-${install_version}.tar.gz
curl -Ls http://downloads.sourceforge.net/project/salesplatform/addons/salesplatform-customerportal-6.4.0-201512.tar.gz?r=http%3A%2F%2Fcommunity.salesplatform.ru%2Fdownload%2F&ts=1453245829&use_mirror=netassist 

# Install SalesPlatform
# and customer portal
tar --strip-components=1 -xzf salesplatform-vtigercrm-${install_version}.tar.gz
tar -xf salesplatform-customerportal-${install_version}.tar.gz
rm -rf salesplatform-vtigercrm-${install_version}.tar.gz
rm -rf salesplatform-customerportal-${install_version}.tar.gz
echo $install_version > ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version

popd >/dev/null
