#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

dest_dir=${OPENSHIFT_DATA_DIR}current

current_version=$(cat ${OPENSHIFT_BUILD_DEPENDENCIES_DIR}.current_version)
install_dir=${OPENSHIFT_BUILD_DEPENDENCIES_DIR}${current_version}

if [ ! -d "${dest_dir}" ]; then
  mkdir -p $dest_dir
  cp -rf ${install_dir}/* ${dest_dir}/
fi

# Replace the php/ directory with provided clean SalesPlatform installation
#
if [ -d ${OPENSHIFT_REPO_DIR}php ]; then
  rm -rf ${OPENSHIFT_REPO_DIR}php
fi
ln -sf ${dest_dir} ${OPENSHIFT_REPO_DIR}php

# Use repository htaccess if exists 

if [  -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ]; then
  cp -f ${OPENSHIFT_REPO_DIR}.openshift/config/.htaccess ${dest_dir}/.htaccess
fi

#set -e

# apply patches

#if [  -d ${OPENSHIFT_REPO_DIR}.openshift/config/patches]; then
  patch ${dest_dir}/modules/Install/views/Index.php    ${OPENSHIFT_REPO_DIR}.openshift/config/patches/db_conf.patch 
#  patch ${dest_dir}/layouts/vlayout/modules/Install/Step4.tpl   ${OPENSHIFT_REPO_DIR}.openshift/config/patches/install_step4_tpl.patch
#  patch ${dest_dir}/languages/ru_ru/Install.php   ${OPENSHIFT_REPO_DIR}.openshift/config/patches/lang_ru_installation_php.patch 
#  patch ${dest_dir}/sd/CustomerAuthenticate.php   ${OPENSHIFT_REPO_DIR}.openshift/config/patches/cp-1.patch
  patch ${dest_dir}/sd/PortalConfig.php   ${OPENSHIFT_REPO_DIR}.openshift/config/patches/cp-2.patch
#  patch ${dest_dir}/config.template.php   ${OPENSHIFT_REPO_DIR}.openshift/config/patches/conf.templ.patch
#fi


if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc cartridge add -a $OPENSHIFT_APP_NAME -c mysql-5.5" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
fi

if [ -z "$OPENSHIFT_MYSQL_DB_HOST" ]
then
    exit 5
fi

# Confirm database exists, if not create it
if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -P "$OPENSHIFT_MYSQL_DB_PORT" -e "select * from vtiger_links;" "$OPENSHIFT_APP_NAME" > /dev/null 2>&1
then
    echo
    echo "Database schema not yet added, SalesPlatform  is ready for install by visiting the site."
else
    echo "Database already configured."
fi
